### ISSUE TITLE
QUESTION: How to Run Migrations & Seeder Properly in Production?

### ISSUE THREAD

**Issue by xfathurrahman** [exaco/laravel-octane-dockerfile#115]
Hi,

First of all, thanks for all your hard work!

I have a noob question here as I’m facing a small issue when setting:

```
RUNNING_MIGRATIONS_AND_SEEDERS=true
```

I’m deploying using a `docker-stack.yaml` file.

## Steps/Procedure:

1. I built a Laravel project using the Docker build command and did it within GitHub Actions:

    ```yaml
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: ./my-app-folder
        push: true
        build-args:
          APP_ENV: production
          WWWUSER: 1000
          WWWGROUP: 1000
        tags: |
          ghcr.io/${{ github.repository_owner }}/my-image:latest
          ghcr.io/${{ github.repository_owner }}/my-image:${{ github.sha }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
    ```

2. I set the `RUNNING_MIGRATIONS_AND_SEEDERS=true` environment variable in the `docker-stack.yaml` file:

    ```yaml
    app:
      image:
        ghcr.io/my-user/my-image:${GIT_COMMIT_HASH:-latest}
      secrets:
        - app-key
        - db-root-password
      environment:
        - RUNNING_MIGRATIONS_AND_SEEDERS=true
        # Other environment variables...
      volumes:
        - storage_app_public:/var/www/html/storage/app/public
        - storage_logs:/var/www/html/storage/logs
    ```

3. Then I ran the Docker stack deploy command:

    ```bash
    docker stack deploy -c docker-stack.yaml --with-registry-auth my-stack --detach=false
    ```

4. Afterward, I created an empty database `db_init` and connected it through the `.env` file.

## Issue/Logs:

The logs show the following:

- with empty database :

<img width="1065" alt="Screenshot 2025-01-10 at 15 14 29" src="https://github.com/user-attachments/assets/9616f627-1cbd-4842-8aaf-10e1bc95b232" />

<img width="1061" alt="Screenshot 2025-01-10 at 15 14 55" src="https://github.com/user-attachments/assets/8ddf32e3-3f5d-4f8f-bdb5-7d8de7c3ded5" />

- with existing database:

<img width="1059" alt="Screenshot 2025-01-10 at 15 19 59" src="https://github.com/user-attachments/assets/48aec00c-1437-40f6-af43-2969141ff810" />

## Question:

Am I missing any steps or best practices when running migrations and seeders in a production environment using this setup? Specifically:

- Should the `RUNNING_MIGRATIONS_AND_SEEDERS=true` variable be handled differently?
- Are there additional configurations required in `docker-stack.yaml` or `.env`?
- What is the intended use case for the RUNNING_MIGRATIONS_AND_SEEDERS environment variable if it does not support migrating and seeding an empty database?
- should we remove --no-dev flags to keep faker ?
```
RUN composer install \
    --classmap-authoritative \
    --no-interaction \
    --no-ansi \
    --no-dev \
    && composer clear-cache
```

Any guidance would be highly appreciated!

Thank you in advance.
